# Go Build
# Copyright Peter Bjorklund 2019
name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout
        uses: actions/checkout@v2

      #- name: Linting
      #  uses: piot/action-go-lint@master

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -count=1 ./...
