# Go Build
# Copyright Peter Bjorklund 2019

name: Release Executables
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Check that version is correct
        id: fetchver
        uses: piot/action-version-from-tag@master

      - name: Install target go version
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out the code
        uses: actions/checkout@v2

      - name: Compile for all platforms
        uses: piot/action-gox@master

      - name: Upload executables
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: build/

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body: "New Release"
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
